# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Builder < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtarchie/translation/releases/download/v0.0.1/builder_darwin_x86_64.tar.gz"
      sha256 "456433deac427a2f1176b3b6ca0e63c996966375f8db0332454258c27124dbc0"

      def install
        bin.install "translation"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtarchie/translation/releases/download/v0.0.1/builder_darwin_arm64.tar.gz"
      sha256 "0106d891a749dbdefa9086d30bd344db559609e81f88800531e3e0f1bfbcd044"

      def install
        bin.install "translation"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/translation/releases/download/v0.0.1/builder_linux_arm64.tar.gz"
      sha256 "4e2f1c32188057d240a8ca0fd8cf8c003ad5100d9330f7ab53204fb6724d729b"

      def install
        bin.install "translation"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jtarchie/translation/releases/download/v0.0.1/builder_linux_x86_64.tar.gz"
      sha256 "d0bfd523459d24504d3e5e798741d35623a7d38f099cae88a0cebb2fefada54d"

      def install
        bin.install "translation"
      end
    end
  end

  test do
    system "#{bin}/translation --help"
  end
end
