# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RailsTranslator < Formula
  desc ""
  homepage ""
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtarchie/translation/releases/download/v0.0.2/rails-translator_darwin_x86_64.tar.gz"
      sha256 "add71b798077f18f83be2c8de6fe0e8d622d56b8b053e1fa02e0ac908cb5a6e3"

      def install
        bin.install "translation"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtarchie/translation/releases/download/v0.0.2/rails-translator_darwin_arm64.tar.gz"
      sha256 "72f1255b03e38ff10107f5cee20a29d4bbe6cda914455b3488cef67315ca82fe"

      def install
        bin.install "translation"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/translation/releases/download/v0.0.2/rails-translator_linux_arm64.tar.gz"
      sha256 "d44a08314bb610a2d5d4a8ad5ca93f6ec1bf6dba4f5a0251419bcca5373bf320"

      def install
        bin.install "translation"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jtarchie/translation/releases/download/v0.0.2/rails-translator_linux_x86_64.tar.gz"
      sha256 "499bc0a21fc97a831cbb2fcb61bb76ff99ac2931bd77919f2cbdfc5613ac051a"

      def install
        bin.install "translation"
      end
    end
  end

  test do
    system "#{bin}/translation --help"
  end
end
