# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RailsTranslator < Formula
  desc ""
  homepage ""
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jtarchie/rails-translator/releases/download/v0.0.5/rails-translator_darwin_arm64.tar.gz"
      sha256 "f52bdb1804d1dee4a5e34bd815a999a9da794f0461893d9940cfab55554f8187"

      def install
        bin.install "translation"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jtarchie/rails-translator/releases/download/v0.0.5/rails-translator_darwin_x86_64.tar.gz"
      sha256 "ec90b97c49461a1bc61eb95611a41ad24bc3dd334c832b5940b1e73fa0814ab5"

      def install
        bin.install "translation"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/rails-translator/releases/download/v0.0.5/rails-translator_linux_arm64.tar.gz"
      sha256 "4e8765ed67375cefe9f081972b25a70b6e056c86087eb0971db86cdc836e8758"

      def install
        bin.install "translation"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jtarchie/rails-translator/releases/download/v0.0.5/rails-translator_linux_x86_64.tar.gz"
      sha256 "8a33fe3f952eb467f54abec8c142258f798f296f46bd4de04690bf6c037ad77a"

      def install
        bin.install "translation"
      end
    end
  end

  test do
    system "#{bin}/translation --help"
  end
end
