version: '3'

tasks:
  build: go build ./...
  generate: go generate ./...
  lint:
    cmds:
    - gofmt -w .
    - golangci-lint run --fix --timeout "10m"
    - deno fmt README.md
  default:
    cmds:
    - task: generate
    - task: lint
    - task: build
    - go run github.com/onsi/ginkgo/v2/ginkgo -r -p --race --cover --tags test
  translate:
    cmds:
    - task: build
    # - ./rails-translator --from-filename examples/en.yaml --to-filename examples/jp.yaml --to-language "Japanese"
    # - ./rails-translator --from-filename examples/en.yaml --to-filename examples/zh.yaml --to-language "Chinese"
    # - ./rails-translator --from-filename examples/en.yaml --to-filename examples/es.yaml --to-language "Spanish"
    # - ./rails-translator --from-filename examples/en.yaml --to-filename examples/es-mx.yaml --to-language "Spanish/Mexico"
    - ./rails-translator --from-filename examples/en.yaml --to-filename examples/jp.gpt4.yaml --to-language "Japanese" --model gpt-4
    - ./rails-translator --from-filename examples/en.yaml --to-filename examples/zh.gpt4.yaml --to-language "Chinese" --model gpt-4
    - ./rails-translator --from-filename examples/en.yaml --to-filename examples/es.gpt4.yaml --to-language "Spanish" --model gpt-4
    - ./rails-translator --from-filename examples/en.yaml --to-filename examples/es-mx.gpt4.yaml --to-language "Spanish/Mexico" --model gpt-4